const stops = [
  {name:"ЖД вокзал Алматы-1",lat:43.340988,lon:76.948907,routes:["2","30","34","36","71","72","73","77","215","223","229","ТП7"],parks:["BAS Trade","АЭТ","Адылет Авто","Досчан М","Мадина","Олжас LTD"],url:"https://go.2gis.com/jPm8a"},
  {name:"Автостанция (Аксай 3Б)",lat:43.235504,lon:76.81809,routes:["65","66","105","110","134","218","238","247"],parks:["Nomad bus","АЭТ","Адылет Авто","Алматы Транс Авто","Нуржас Транс"],url:"https://go.2gis.com/8DnxC"},
  {name:"Рынок Барлык",lat:43.227411,lon:76.771452,routes:["44","47","55","76","128","246"],parks:["АЭТ","Адылет Авто","Думан транс.com2019","Мадина","Нуржас Транс"],url:"https://go.2gis.com/mlHqF"},
  {name:"Айнабулак-3 (верхняя)",lat:43.328763,lon:76.923598,routes:["17","80","120","141","120А"],parks:["АЭТ","Думан транс KZ","Олжас LTD"],url:"https://go.2gis.com/A0In1"},
  {name:"Автостанция (мкр.Жулдыз)",lat:43.36056,lon:76.99048,routes:["32","51","85","121"],parks:["АЭТ","Самат транс","Тулпар ЦДС"],url:"https://go.2gis.com/tMmhP"},
  {name:"гор.больница №7",lat:43.233823,lon:76.799514,routes:["83","84","130","84А"],parks:["АЭТ"],url:"https://go.2gis.com/mBB7v"},
  {name:"ЖД вокзал Алматы-2",lat:43.273786,lon:76.939044,routes:["91","145","ТП5","ТП6"],parks:["АЭТ"],url:"https://go.2gis.com/CuHxm"},
  {name:"рынок Жетысу",lat:43.301528,lon:77.005772,routes:["59","69","113","138"],parks:["АЭТ","Думан транс.com2019"],url:"https://go.2gis.com/wktOW"},
  {name:"ул.Солнечная",lat:43.357018,lon:76.917587,routes:["41","70","123","125"],parks:["BAS Trade","АЭТ"],url:"https://go.2gis.com/zT4zY"},

  {name:"Метро Райымбек батыра",lat:43.272599,lon:76.94505,routes:["9","140","220"],parks:["Nomad bus","Досчан М","Думан транс KZ"],url:"https://go.2gis.com/Ivyth"},

  {name:"А/С Арман",lat:43.195503,lon:76.896991,routes:["135","63А"],parks:["АЭТ"],url:"https://go.2gis.com/2yKqp"},
  {name:"Аэропорт",lat:43.345963,lon:77.01184,routes:["3","92"],parks:["АЭТ"],url:"https://go.2gis.com/bwlOm"},
  {name:"Бурундайский Аэропорт",lat:43.355624,lon:76.875227,routes:["10","10А"],parks:["АЭТ"],url:"https://go.2gis.com/ldhmn"},
  {name:"Гиперм. \"Magnum\"",lat:43.291477,lon:77.011463,routes:["37","65"],parks:["АЭТ"],url:"https://go.2gis.com/hLDdN"},
  {name:"Дворец спорта",lat:43.239388,lon:76.92779,routes:["209","210"],parks:["АЭТ"],url:"https://go.2gis.com/dptO0"},
  {name:"Думан-восток / Бурабай",lat:43.282719,lon:77.01123,routes:["11","17"],parks:["Думан транс KZ","Думан транс.com2019"],url:"https://go.2gis.com/ib22U"},
  {name:"Жандосова/Саина",lat:43.208762,lon:76.864617,routes:["79","ТП12"],parks:["АЭТ"],url:"https://go.2gis.com/uouW6"},
  {name:"жд МОСТ",lat:43.343015,lon:76.948489,routes:["13","74"],parks:["АЭТ","КИИКБАЙ"],url:"https://go.2gis.com/ou9uL"},
  {name:"Кооптехникум",lat:43.168236,lon:76.876967,routes:["119","139"],parks:["Авто Алма Транс","Олжас LTD"],url:"https://go.2gis.com/Xhccc"},
  {name:"мкр. Айша-Биби",lat:43.308049,lon:76.976237,routes:["50","93"],parks:["АЭТ","Думан транс.com2019"],url:"https://go.2gis.com/PrmBx"},
  {name:"мкр. Асыл Арман",lat:43.228649,lon:76.753597,routes:["14","16"],parks:["АЭТ","Досчан М"],url:"https://go.2gis.com/YKr1C"},
  {name:"мкр.Абай",lat:43.208418,lon:76.775297,routes:["31","67"],parks:["Автобусный парк №2"],url:"https://go.2gis.com/DEjQT"},
  {name:"Плотина (мкр.Карагайлы)",lat:43.139424,lon:76.8646,routes:["14","39"],parks:["Алматы Транс Авто","Досчан М"],url:"https://go.2gis.com/wGmjI"},
  {name:"ст.м.Бауржан Момышулы",lat:43.216638,lon:76.838442,routes:["61","136"],parks:["АЭТ"],url:"https://go.2gis.com/4NXVg"},
  {name:"Таможня",lat:43.360885,lon:77.019097,routes:["86","87"],parks:["Nomad bus","АЭТ"],url:"https://go.2gis.com/pa1Hb"},
  {name:"ул. Утемисова",lat:43.310117,lon:76.865939,routes:["45","103"],parks:["АЭТ"],url:"https://go.2gis.com/3ERAE"},
  {name:"ул.Маргулана",lat:43.232548,lon:76.830994,routes:["ТП11","ТП25"],parks:["АЭТ"],url:"https://go.2gis.com/PDP5G"},
  {name:"Хантенгри/Казыгурт",lat:43.278432,lon:76.99943,routes:["4","62"],parks:["Авто Алма Транс","Олжас LTD"],url:"https://go.2gis.com/iNEoa"},

  {name:"\"Ой-Карагай\"-Восток",lat:null,lon:null,routes:["210"],parks:["АЭТ"],url:"https://go.2gis.com/cH71w"},
  {name:"Алатау / Абая",lat:43.201814,lon:76.794136,routes:["137"],parks:["АЭТ"],url:"https://go.2gis.com/OYNky"},
  {name:"Алатау/Абая",lat:null,lon:null,routes:["27"],parks:["Адылет Авто"],url:"https://go.2gis.com/hz4zq"},
  {name:"Ашимова/Райымбека",lat:null,lon:null,routes:["26"],parks:["Сапаршы"],url:"https://go.2gis.com/H55B3"},
  {name:"Березовая роща",lat:null,lon:null,routes:["5В"],parks:["Сапаршы"],url:"https://go.2gis.com/t6K1S"},
  {name:"Больница (г.Талгар)",lat:null,lon:null,routes:["203"],parks:["Думан транс KZ"],url:"https://go.2gis.com/XK7h9"},
  {name:"Всемирная Академия бокса",lat:null,lon:null,routes:["224"],parks:["Думан транс KZ"],url:"https://go.2gis.com/wH5Kh"},
  {name:"Горный курорт \"Пионер\"",lat:null,lon:null,routes:["209"],parks:["АЭТ"],url:"https://go.2gis.com/K5Fd2"},
  {name:"Дачи-4",lat:null,lon:null,routes:["11"],parks:["Думан транс.com2019"],url:"https://go.2gis.com/5BjT7"},
  {name:"Дворец спорта",lat:null,lon:null,routes:["21"],parks:["АЭТ"],url:"https://go.2gis.com/LPMwB"},
  {name:"Жас-Канат ЮГ",lat:null,lon:null,routes:["27"],parks:["Адылет Авто"],url:"https://go.2gis.com/zlvaD"},
  {name:"ЖК \"Ashyq Tobe\"",lat:null,lon:null,routes:["232"],parks:["Тулпар ЦДС"],url:"https://go.2gis.com/O7zCf"},
  {name:"ЖК \"Аспан Сити\"",lat:null,lon:null,routes:["54"],parks:["Авто Алма Транс"],url:"https://go.2gis.com/zuyGt"},
  {name:"ЖК \"Бай-Тал\"",lat:null,lon:null,routes:["63"],parks:["АЭТ"],url:"https://go.2gis.com/yvQcl"},
  {name:"Каирбекова/Жибек Жолы",lat:null,lon:null,routes:["43"],parks:["АЭТ"],url:"https://go.2gis.com/dNxhM"},
  {name:"Калдаякова/Жибек Жолы",lat:null,lon:null,routes:["60"],parks:["Адылет Авто"],url:"https://go.2gis.com/iTODJ"},
  {name:"Карасу-Север",lat:null,lon:null,routes:["35"],parks:["АЭТ"],url:"https://go.2gis.com/AWlO0"},
  {name:"кафе \"Дамде\"",lat:null,lon:null,routes:["230"],parks:["Каскеленский парк"],url:"https://go.2gis.com/yvVWA"},
  {name:"колледж с.Шамалган",lat:null,lon:null,routes:["212"],parks:["Neo city Trans"],url:"https://go.2gis.com/K5I8R"},
  {name:"Конд. фабрика \"Рахат\"",lat:null,lon:null,routes:["129"],parks:["Думан транс KZ"],url:"https://go.2gis.com/JNriR"},
  {name:"мкр.Актобе",lat:null,lon:null,routes:["5"],parks:["Сапаршы"],url:"https://go.2gis.com/N1wAZ"},
  {name:"мкр.Альмерек",lat:null,lon:null,routes:["106"],parks:["Тулпар ЦДС"],url:"https://go.2gis.com/9fREr"},
  {name:"мкр.Водник",lat:null,lon:null,routes:["124"],parks:["АЭТ"],url:"https://go.2gis.com/dWcdB"},
  {name:"мкр.Казахфильм",lat:null,lon:null,routes:["127"],parks:["АЭТ"],url:"https://go.2gis.com/IvGQj"},
  {name:"мкр.Кольсай",lat:null,lon:null,routes:["107"],parks:["АЭТ"],url:"https://go.2gis.com/2dKtn"},
  {name:"мкр.Нурлытау",lat:null,lon:null,routes:["116"],parks:["Алматы Транс Авто"],url:"https://go.2gis.com/oRvhq"},
  {name:"мкр.Саялы-2-Запад",lat:null,lon:null,routes:["33"],parks:["Тулпар ЦДС"],url:"https://go.2gis.com/4CpWC"},
  {name:"мкр.Таужолы",lat:null,lon:null,routes:["26"],parks:["Сапаршы"],url:"https://go.2gis.com/k2jby"},
  {name:"Монке би/Онгарсыновой",lat:null,lon:null,routes:["201"],parks:["АЭТ"],url:"https://go.2gis.com/3J95t"},
  {name:"По требованию (алма арасан)",lat:null,lon:null,routes:["211"],parks:["АЭТ"],url:"https://go.2gis.com/zJJRS"},
  {name:"Разворотная площадка (село байкент)",lat:null,lon:null,routes:["233"],parks:["BAS Trade"],url:"https://go.2gis.com/2U775"},
  {name:"Рыскулова/Жангельдина",lat:null,lon:null,routes:["38"],parks:["АЭТ"],url:"https://go.2gis.com/wmIzA"},
  {name:"Рыскулова/Кунаева (г.Талгар)",lat:null,lon:null,routes:["207"],parks:["Думан транс KZ"],url:"https://go.2gis.com/t4ugR"},
  {name:"Рыскулова/Шемякина",lat:null,lon:null,routes:["38А"],parks:["АЭТ"],url:"https://go.2gis.com/mhbcP"},
  {name:"Сан.Ак-Кайын",lat:null,lon:null,routes:["5Б"],parks:["Сапаршы"],url:"https://go.2gis.com/LuWGE"},
  {name:"Северное кольцо",lat:null,lon:null,routes:["254"],parks:["Мадина"],url:"https://go.2gis.com/QPzEL"},
  {name:"Село Ай-Абылай",lat:null,lon:null,routes:["222"],parks:["Думан транс KZ"],url:"https://go.2gis.com/ESYhz"},
  {name:"Село Аксай",lat:null,lon:null,routes:["227"],parks:["Досчан М"],url:"https://go.2gis.com/ztESw"},
  {name:"Село Али",lat:null,lon:null,routes:["217"],parks:["КИИКБАЙ"],url:"https://go.2gis.com/i83IT"},
  {name:"Село Алмалыбак",lat:null,lon:null,routes:["239"],parks:["Neo city Trans"],url:"https://go.2gis.com/jdIWX"},
  {name:"Село Базаркельды",lat:null,lon:null,routes:["242"],parks:["Жас Транс"],url:"https://go.2gis.com/EIv5t"},
  {name:"Село Батыр",lat:null,lon:null,routes:["240"],parks:["BAS Trade"],url:"https://go.2gis.com/ma59Z"},
  {name:"Село Баяндай",lat:null,lon:null,routes:["243"],parks:["BAS Trade"],url:"https://go.2gis.com/LQWBe"},
  {name:"Село Даулет",lat:null,lon:null,routes:["216"],parks:["КИИКБАЙ"],url:"https://go.2gis.com/RnARR"},
  {name:"Село Еламан",lat:null,lon:null,routes:["234"],parks:["Самат транс"],url:"https://go.2gis.com/eB1Fw"},
  {name:"Село Енбекши",lat:null,lon:null,routes:["257"],parks:["D Autobus Trans"],url:"https://go.2gis.com/ZaWtD"},
  {name:"Село Жалпаксай",lat:null,lon:null,routes:["78"],parks:["Каскеленский парк"],url:"https://go.2gis.com/2tE8W"},
  {name:"Село Жанатурмыс",lat:null,lon:null,routes:["226"],parks:["Думан транс KZ"],url:"https://go.2gis.com/6XlTD"},
  {name:"Село Жаугашты",lat:null,lon:null,routes:["255"],parks:["Нуржас Транс"],url:"https://go.2gis.com/d6Y9c"},
  {name:"Село Жомарт",lat:null,lon:null,routes:["251"],parks:["BAS Trade"],url:"https://go.2gis.com/JRNpc"},
  {name:"Село Кайнар",lat:null,lon:null,routes:["244"],parks:["Каскеленский парк"],url:"https://go.2gis.com/XyzJP"},
  {name:"Село Кайнар",lat:null,lon:null,routes:["221"],parks:["Самат транс"],url:"https://go.2gis.com/YDrke"},
  {name:"Село Карасу",lat:null,lon:null,routes:["219"],parks:["Самат транс"],url:"https://go.2gis.com/8czxQ"},
  {name:"Село Каратобе",lat:null,lon:null,routes:["237"],parks:["D Autobus Trans"],url:"https://go.2gis.com/n1UcW"},
  {name:"Село Каргалы. Запад",lat:null,lon:null,routes:["236"],parks:["Neo city Trans"],url:"https://go.2gis.com/oOG3G"},
  {name:"Село Кемертоган",lat:null,lon:null,routes:["53"],parks:["Neo city Trans"],url:"https://go.2gis.com/Ehe2K"},
  {name:"Село Койшибек",lat:null,lon:null,routes:["241"],parks:["Жас Транс"],url:"https://go.2gis.com/kvnwr"},
  {name:"село коктобе",lat:null,lon:null,routes:["225"],parks:["BAS Trade"],url:"https://go.2gis.com/dO96A"},
  {name:"Село Кольащы",lat:null,lon:null,routes:["213"],parks:["Досчан М"],url:"https://go.2gis.com/6QuPv"},
  {name:"Село Комсомол",lat:null,lon:null,routes:["231"],parks:["Досчан М"],url:"https://go.2gis.com/8VLl9"},
  {name:"Село Кыргаулды",lat:null,lon:null,routes:["250"],parks:["Нуржас Транс"],url:"https://go.2gis.com/WXT1H"},
  {name:"Село Остемир",lat:null,lon:null,routes:["258"],parks:["Самат транс"],url:"https://go.2gis.com/vJ5e5"},
  {name:"Село Шолаккаргалы",lat:null,lon:null,routes:["248"],parks:["Нуржас Транс"],url:"https://go.2gis.com/OLaE2"},
  {name:"Спорткомплекс \"Медеу\"",lat:null,lon:null,routes:["12"],parks:["АЭТ"],url:"https://go.2gis.com/TciSC"},
  {name:"ст.м.Сайран",lat:null,lon:null,routes:["132"],parks:["Думан транс.com2019"],url:"https://go.2gis.com/IDnJY"},
  {name:"торговый центр (мкр.Алатау)",lat:null,lon:null,routes:["117"],parks:["Самат транс"],url:"https://go.2gis.com/WDzLc"},
  {name:"ТЦ \"Тоймарт\"",lat:null,lon:null,routes:["56"],parks:["АЭТ"],url:"https://go.2gis.com/DEkoy"},
  {name:"ул. Абдуллиных",lat:null,lon:null,routes:["114"],parks:["Адылет Авто"],url:"https://go.2gis.com/8a7zz"},
  {name:"ул. Абдуллиных",lat:null,lon:null,routes:["5А"],parks:["Сапаршы"],url:"https://go.2gis.com/ITfTa"},
  {name:"ул. Аксункар",lat:null,lon:null,routes:["81"],parks:["Автобусный парк №2"],url:"https://go.2gis.com/gJkBj"},
  {name:"ул. Алматинская",lat:null,lon:null,routes:["68"],parks:["Автобусный парк №2"],url:"https://go.2gis.com/Qn27I"},
  {name:"ул. Бектембая",lat:null,lon:null,routes:["126"],parks:["АЭТ"],url:"https://go.2gis.com/jkUKo"},
  {name:"ул. Гончарова",lat:null,lon:null,routes:["40"],parks:["Адылет Авто"],url:"https://go.2gis.com/tpNpb"},
  {name:"ул. Есенберлина",lat:null,lon:null,routes:["8"],parks:["Авто Алма Транс"],url:"https://go.2gis.com/pcmoH"},
  {name:"ул. Есентайская",lat:null,lon:null,routes:["20"],parks:["Думан транс KZ"],url:"https://go.2gis.com/Ik28i"},
  {name:"ул. Жанаарка",lat:null,lon:null,routes:["75"],parks:["Думан транс.com2019"],url:"https://go.2gis.com/cKC4o"},
  {name:"ул. Иштвана Коныра",lat:null,lon:null,routes:["131"],parks:["Думан транс.com2019"],url:"https://go.2gis.com/CozeS"},
  {name:"ул. Карьерная",lat:null,lon:null,routes:["49"],parks:["Neo city Trans"],url:"https://go.2gis.com/BTCH7"},
  {name:"ул. Кожабекова",lat:43.200462,lon:76.895179,routes:["ТП1"],parks:["АЭТ"],url:"https://go.2gis.com/MalrG"},
  {name:"ул. Космонавтов (с.Еркин)",lat:null,lon:null,routes:["228"],parks:["Самат транс"],url:"https://go.2gis.com/FonLv"},
  {name:"ул. Мира",lat:null,lon:null,routes:["90"],parks:["АЭТ"],url:"https://go.2gis.com/hHQ8L"},
  {name:"ул. Пушкина (с.Бельбулак)",lat:null,lon:null,routes:["204"],parks:["Думан транс KZ"],url:"https://go.2gis.com/Kf60N"},
  {name:"ул. Станиславского",lat:null,lon:null,routes:["111"],parks:["Думан транс KZ"],url:"https://go.2gis.com/Vgpd1"},
  {name:"ул.Бидайык",lat:null,lon:null,routes:["104"],parks:["Олжас LTD"],url:"https://go.2gis.com/aRVyX"},
  {name:"ул.Кожабекова",lat:null,lon:null,routes:["ТП9"],parks:["АЭТ"],url:"https://go.2gis.com/2Vpok"},
  {name:"ул.Саги Ашимова",lat:null,lon:null,routes:["ТП19"],parks:["АЭТ"],url:"https://go.2gis.com/AUSKR"},
  {name:"ул.Строительная",lat:null,lon:null,routes:["118"],parks:["АЭТ"],url:"https://go.2gis.com/fYfFj"},
  {name:"Школа",lat:null,lon:null,routes:["235"],parks:["Досчан М"],url:"https://go.2gis.com/HXM8I"},
  {name:"Школа -гимназия №209",lat:null,lon:null,routes:["96"],parks:["АЭТ"],url:"https://go.2gis.com/iPYz5"},
  {name:"Школа №184",lat:null,lon:null,routes:["115"],parks:["АЭТ"],url:"https://go.2gis.com/1fqdU"},
  {name:"школа №218",lat:null,lon:null,routes:["58"],parks:["Думан транс KZ"],url:"https://go.2gis.com/iBNV7"},
  {name:"Экопост",lat:null,lon:null,routes:["24"],parks:["АЭТ"],url:"https://go.2gis.com/PvF6y"}
];